[tool.black]
line-length = 79
skip-string-normalization = true
force-exclude = '''
(
  migrations/
  | .*settings.py
)
'''

[tool.isort]
profile = 'black'
line_length = 79
extend_skip = ['migrations']
known_local_folder = ['foodgram', 'users', 'recipes']