# Generated by Django 4.1.1 on 2022-10-09 16:43

from django.db import migrations
import recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.HEXColorField(max_length=7, unique=True),
        ),
    ]
